name: Your New Jekyll Site
markdown: redcarpet
pygments: true

prose:
  rooturl: 'source/_posts'
  siteurl: 'http://techblog.trunkclub.com'
  media: 'assets'
  metadata:
    source/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "Trunk Botterson"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true