name: Your New Jekyll Site
markdown: redcarpet
pygments: true


prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "review"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""