name: Dear Cast & Crew
markdown: redcarpet
pygments: true

prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "review"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""